# **TP08 SVM (Support vector Machine)**

## **Partie 1**

#### Q1. Récupération des données

1-Utiliser load_iris  de la librairie sklearn.datasets pour récuperer les données de ce fichier 

2-Afficher les variables explicatives et et la variable explicatives.




In [2]:
#1
from sklearn.datasets import load_iris
dt=load_iris()

In [7]:
x,y=dt.data,dt.target

In [13]:
#2
#les variable explicatif
dt.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [14]:
dt.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

#### Q2. Selection des caracteristiques
Créer les deux dataframes:
- X: le dataframe des entrée 
- y: la sortie 

In [18]:
import numpy as np
x=np.array(dt.data)
y=np.array(dt.target)

#### Q3. Partitionner ces données en X_train, X_test, y_train, y_test

In [19]:
from sklearn.model_selection import train_test_split as tts
x_train,x_test,y_train,y_test=tts(x,y,train_size=0.9)

#### Q4. Création, entrainement et évaluation du modèle SVM
1. Utiliser le classifieur ***svm*** du module ***sklearn*** pour initialiser et entrainer quatres modèles svm avec les parametres suivants:
>- kernel: "linear";  C: 1
>- kernel: "linear";  C: 10 ; gamma=10
>- kernel: "rbf"   ;  C: 1 ; gamma=10
>- kernel: "rbf"   ;  C: 3

In [25]:
from sklearn import svm
mdl1=svm.SVC(kernel="linear",C=1).fit(x_train,y_train)
mdl2=svm.SVC(kernel="linear",C=10,gamma=10).fit(x_train,y_train)
mdl3=svm.SVC(kernel="rbf",C=1,gamma=10).fit(x_train,y_train)
mdl4=svm.SVC(kernel="rbf",C=3).fit(x_train,y_train)

In [26]:
mdl1.score(x_train,y_train)

0.9777777777777777

In [27]:
mdl2.score(x_train,y_train)

0.9703703703703703

In [28]:
mdl3.score(x_train,y_train)

1.0

In [29]:
mdl4.score(x_train,y_train)

0.9925925925925926

#### Q5. Comparaison des deux modèles
1. pour chacun des quatres modèles, afficher la matrice de confusion

2. Quel est le meilleur modèle pour ce problème? pourquoi?

In [42]:
#1
from sklearn.metrics import confusion_matrix
print("matrice de confusion:")
print("cas 1: \n{}\n".format(confusion_matrix(y_test, mdl1.predict(x_test) )))
print("cas 2: \n{}\n".format(confusion_matrix(y_test, mdl2.predict(x_test) )))
print("cas 3: \n{}\n".format(confusion_matrix(y_test, mdl3.predict(x_test) )))
print("cas 4: \n{}\n".format(confusion_matrix(y_test, mdl4.predict(x_test) )))

matrice de confusion:
cas 1: 
[[8 0 0]
 [0 5 0]
 [0 0 2]]

cas 2: 
[[8 0 0]
 [0 5 0]
 [0 0 2]]

cas 3: 
[[7 0 1]
 [0 4 1]
 [0 0 2]]

cas 4: 
[[8 0 0]
 [0 5 0]
 [0 0 2]]



## **Partie II**

Entraînez le classificateur SVM à l'aide de l'ensemble de données sklearn digits (c'est-à-dire à partir de sklearn.datasets import load_digits), 
- Partitionner ces données en X_train, X_test, y_train, y_test
- Mesurez accurancy de votre modèle à l'aide de différents kernels tels que rbf et linear.
-Ajustez davantage votre modèle en utilisant les paramètres de régularisation et gamma et essayez d'obtenir le score de précision le plus élevé

In [43]:
from sklearn.datasets import load_digits
dt2=load_digits()

In [45]:
X,Y=np.array(dt2.data),np.array(dt2.target)

In [48]:
X_train,X_test,Y_train,Y_test=tts(X,Y,train_size=0.9)

In [49]:
model1=svm.SVC(kernel="linear",C=1).fit(X_train,Y_train)
model2=svm.SVC(kernel="rbf",C=1).fit(X_train,Y_train)

In [51]:
print("accuracy score of model1:",model1.score(X_train,Y_train))
print("accuracy score of model2:",model2.score(X_train,Y_train))

accuracy score of model1: 1.0
accuracy score of model2: 0.9969078540507111


In [52]:
model3=svm.SVC(kernel="linear",C=1,gamma=10).fit(X_train,Y_train)
model4=svm.SVC(kernel="rbf",C=1,gamma=10).fit(X_train,Y_train)

In [55]:
print("our model with gamma")
print("accuracy score of model3:",model3.score(X_train,Y_train))
print("accuracy score of model4:",model4.score(X_train,Y_train))

our model with gamma
accuracy score of model3: 1.0
accuracy score of model4: 1.0
